/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestion_election (void)
{
  GtkWidget *gestion_election;
  GtkWidget *fixed78;
  GtkWidget *button277;
  GtkWidget *alignment204;
  GtkWidget *hbox204;
  GtkWidget *image233;
  GtkWidget *label836;
  GtkWidget *button278;
  GtkWidget *alignment208;
  GtkWidget *hbox208;
  GtkWidget *image237;
  GtkWidget *label840;
  GtkWidget *button279;
  GtkWidget *alignment209;
  GtkWidget *hbox209;
  GtkWidget *image238;
  GtkWidget *label841;
  GtkWidget *button280;
  GtkWidget *alignment210;
  GtkWidget *hbox210;
  GtkWidget *image239;
  GtkWidget *label842;
  GtkWidget *label843;
  GtkWidget *rech_gest_elec_entry;
  GtkWidget *treeview1;
  GtkWidget *rech1_gest_elec_entry;
  GtkWidget *rech2_gest_elec_entry;
  GtkWidget *rech1_gest_elec_button;
  GtkWidget *supp_gest_elec_button;
  GtkWidget *alignment237;
  GtkWidget *hbox237;
  GtkWidget *image268;
  GtkWidget *label888;
  GtkWidget *ajout_gest_elec_button;
  GtkWidget *alignment236;
  GtkWidget *hbox236;
  GtkWidget *image267;
  GtkWidget *label887;
  GtkWidget *modif_gest_elec_button;
  GtkWidget *alignment235;
  GtkWidget *hbox235;
  GtkWidget *image266;
  GtkWidget *label886;
  GtkWidget *rech2_gest_elec_button;

  gestion_election = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_election), _("gestion des elections "));

  fixed78 = gtk_fixed_new ();
  gtk_widget_show (fixed78);
  gtk_container_add (GTK_CONTAINER (gestion_election), fixed78);

  button277 = gtk_button_new ();
  gtk_widget_show (button277);
  gtk_fixed_put (GTK_FIXED (fixed78), button277, 376, 16);
  gtk_widget_set_size_request (button277, 136, 48);

  alignment204 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment204);
  gtk_container_add (GTK_CONTAINER (button277), alignment204);

  hbox204 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox204);
  gtk_container_add (GTK_CONTAINER (alignment204), hbox204);

  image233 = gtk_image_new_from_stock ("gtk-page-setup", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image233);
  gtk_box_pack_start (GTK_BOX (hbox204), image233, FALSE, FALSE, 0);

  label836 = gtk_label_new_with_mnemonic (_("Administration "));
  gtk_widget_show (label836);
  gtk_box_pack_start (GTK_BOX (hbox204), label836, FALSE, FALSE, 0);

  button278 = gtk_button_new ();
  gtk_widget_show (button278);
  gtk_fixed_put (GTK_FIXED (fixed78), button278, 32, 16);
  gtk_widget_set_size_request (button278, 152, 48);

  alignment208 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment208);
  gtk_container_add (GTK_CONTAINER (button278), alignment208);

  hbox208 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox208);
  gtk_container_add (GTK_CONTAINER (alignment208), hbox208);

  image237 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image237);
  gtk_box_pack_start (GTK_BOX (hbox208), image237, FALSE, FALSE, 0);

  label840 = gtk_label_new_with_mnemonic (_("Accueil "));
  gtk_widget_show (label840);
  gtk_box_pack_start (GTK_BOX (hbox208), label840, FALSE, FALSE, 0);

  button279 = gtk_button_new ();
  gtk_widget_show (button279);
  gtk_fixed_put (GTK_FIXED (fixed78), button279, 544, 16);
  gtk_widget_set_size_request (button279, 152, 48);

  alignment209 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment209);
  gtk_container_add (GTK_CONTAINER (button279), alignment209);

  hbox209 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox209);
  gtk_container_add (GTK_CONTAINER (alignment209), hbox209);

  image238 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image238);
  gtk_box_pack_start (GTK_BOX (hbox209), image238, FALSE, FALSE, 0);

  label841 = gtk_label_new_with_mnemonic (_("profile"));
  gtk_widget_show (label841);
  gtk_box_pack_start (GTK_BOX (hbox209), label841, FALSE, FALSE, 0);

  button280 = gtk_button_new ();
  gtk_widget_show (button280);
  gtk_fixed_put (GTK_FIXED (fixed78), button280, 728, 16);
  gtk_widget_set_size_request (button280, 160, 48);

  alignment210 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment210);
  gtk_container_add (GTK_CONTAINER (button280), alignment210);

  hbox210 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox210);
  gtk_container_add (GTK_CONTAINER (alignment210), hbox210);

  image239 = gtk_image_new_from_stock ("gtk-connect", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image239);
  gtk_box_pack_start (GTK_BOX (hbox210), image239, FALSE, FALSE, 0);

  label842 = gtk_label_new_with_mnemonic (_("Se deconnecter "));
  gtk_widget_show (label842);
  gtk_box_pack_start (GTK_BOX (hbox210), label842, FALSE, FALSE, 0);

  label843 = gtk_label_new (_("gestion des elections "));
  gtk_widget_show (label843);
  gtk_fixed_put (GTK_FIXED (fixed78), label843, 248, 80);
  gtk_widget_set_size_request (label843, 416, 56);

  rech_gest_elec_entry = gtk_entry_new ();
  gtk_widget_show (rech_gest_elec_entry);
  gtk_fixed_put (GTK_FIXED (fixed78), rech_gest_elec_entry, 24, 192);
  gtk_widget_set_size_request (rech_gest_elec_entry, 240, 40);
  gtk_entry_set_text (GTK_ENTRY (rech_gest_elec_entry), _("Rechercher "));
  gtk_entry_set_invisible_char (GTK_ENTRY (rech_gest_elec_entry), 8226);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed78), treeview1, 24, 256);
  gtk_widget_set_size_request (treeview1, 300, 200);

  rech1_gest_elec_entry = gtk_entry_new ();
  gtk_widget_show (rech1_gest_elec_entry);
  gtk_fixed_put (GTK_FIXED (fixed78), rech1_gest_elec_entry, 416, 200);
  gtk_widget_set_size_request (rech1_gest_elec_entry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (rech1_gest_elec_entry), 8226);

  rech2_gest_elec_entry = gtk_entry_new ();
  gtk_widget_show (rech2_gest_elec_entry);
  gtk_fixed_put (GTK_FIXED (fixed78), rech2_gest_elec_entry, 632, 200);
  gtk_widget_set_size_request (rech2_gest_elec_entry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (rech2_gest_elec_entry), 8226);

  rech1_gest_elec_button = gtk_check_button_new_with_mnemonic (_("nom municipalite"));
  gtk_widget_show (rech1_gest_elec_button);
  gtk_fixed_put (GTK_FIXED (fixed78), rech1_gest_elec_button, 272, 200);
  gtk_widget_set_size_request (rech1_gest_elec_button, 144, 32);

  supp_gest_elec_button = gtk_button_new ();
  gtk_widget_show (supp_gest_elec_button);
  gtk_fixed_put (GTK_FIXED (fixed78), supp_gest_elec_button, 512, 360);
  gtk_widget_set_size_request (supp_gest_elec_button, 104, 37);

  alignment237 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment237);
  gtk_container_add (GTK_CONTAINER (supp_gest_elec_button), alignment237);

  hbox237 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox237);
  gtk_container_add (GTK_CONTAINER (alignment237), hbox237);

  image268 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image268);
  gtk_box_pack_start (GTK_BOX (hbox237), image268, FALSE, FALSE, 0);

  label888 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label888);
  gtk_box_pack_start (GTK_BOX (hbox237), label888, FALSE, FALSE, 0);

  ajout_gest_elec_button = gtk_button_new ();
  gtk_widget_show (ajout_gest_elec_button);
  gtk_fixed_put (GTK_FIXED (fixed78), ajout_gest_elec_button, 512, 272);
  gtk_widget_set_size_request (ajout_gest_elec_button, 104, 29);

  alignment236 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment236);
  gtk_container_add (GTK_CONTAINER (ajout_gest_elec_button), alignment236);

  hbox236 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox236);
  gtk_container_add (GTK_CONTAINER (alignment236), hbox236);

  image267 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image267);
  gtk_box_pack_start (GTK_BOX (hbox236), image267, FALSE, FALSE, 0);

  label887 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label887);
  gtk_box_pack_start (GTK_BOX (hbox236), label887, FALSE, FALSE, 0);

  modif_gest_elec_button = gtk_button_new ();
  gtk_widget_show (modif_gest_elec_button);
  gtk_fixed_put (GTK_FIXED (fixed78), modif_gest_elec_button, 512, 320);
  gtk_widget_set_size_request (modif_gest_elec_button, 104, 29);

  alignment235 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment235);
  gtk_container_add (GTK_CONTAINER (modif_gest_elec_button), alignment235);

  hbox235 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox235);
  gtk_container_add (GTK_CONTAINER (alignment235), hbox235);

  image266 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image266);
  gtk_box_pack_start (GTK_BOX (hbox235), image266, FALSE, FALSE, 0);

  label886 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label886);
  gtk_box_pack_start (GTK_BOX (hbox235), label886, FALSE, FALSE, 0);

  rech2_gest_elec_button = gtk_check_button_new_with_mnemonic (_("id"));
  gtk_widget_show (rech2_gest_elec_button);
  gtk_fixed_put (GTK_FIXED (fixed78), rech2_gest_elec_button, 584, 200);
  gtk_widget_set_size_request (rech2_gest_elec_button, 48, 24);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) rech1_gest_elec_button, "toggled",
                    G_CALLBACK (on_rech1_gest_elec_button_toggled),
                    NULL);
  g_signal_connect ((gpointer) supp_gest_elec_button, "clicked",
                    G_CALLBACK (on_supp_gest_elec_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajout_gest_elec_button, "clicked",
                    G_CALLBACK (on_ajout_gest_elec_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) modif_gest_elec_button, "clicked",
                    G_CALLBACK (on_modif_gest_elec_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) rech2_gest_elec_button, "toggled",
                    G_CALLBACK (on_rech2_gest_elec_button_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_election, gestion_election, "gestion_election");
  GLADE_HOOKUP_OBJECT (gestion_election, fixed78, "fixed78");
  GLADE_HOOKUP_OBJECT (gestion_election, button277, "button277");
  GLADE_HOOKUP_OBJECT (gestion_election, alignment204, "alignment204");
  GLADE_HOOKUP_OBJECT (gestion_election, hbox204, "hbox204");
  GLADE_HOOKUP_OBJECT (gestion_election, image233, "image233");
  GLADE_HOOKUP_OBJECT (gestion_election, label836, "label836");
  GLADE_HOOKUP_OBJECT (gestion_election, button278, "button278");
  GLADE_HOOKUP_OBJECT (gestion_election, alignment208, "alignment208");
  GLADE_HOOKUP_OBJECT (gestion_election, hbox208, "hbox208");
  GLADE_HOOKUP_OBJECT (gestion_election, image237, "image237");
  GLADE_HOOKUP_OBJECT (gestion_election, label840, "label840");
  GLADE_HOOKUP_OBJECT (gestion_election, button279, "button279");
  GLADE_HOOKUP_OBJECT (gestion_election, alignment209, "alignment209");
  GLADE_HOOKUP_OBJECT (gestion_election, hbox209, "hbox209");
  GLADE_HOOKUP_OBJECT (gestion_election, image238, "image238");
  GLADE_HOOKUP_OBJECT (gestion_election, label841, "label841");
  GLADE_HOOKUP_OBJECT (gestion_election, button280, "button280");
  GLADE_HOOKUP_OBJECT (gestion_election, alignment210, "alignment210");
  GLADE_HOOKUP_OBJECT (gestion_election, hbox210, "hbox210");
  GLADE_HOOKUP_OBJECT (gestion_election, image239, "image239");
  GLADE_HOOKUP_OBJECT (gestion_election, label842, "label842");
  GLADE_HOOKUP_OBJECT (gestion_election, label843, "label843");
  GLADE_HOOKUP_OBJECT (gestion_election, rech_gest_elec_entry, "rech_gest_elec_entry");
  GLADE_HOOKUP_OBJECT (gestion_election, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (gestion_election, rech1_gest_elec_entry, "rech1_gest_elec_entry");
  GLADE_HOOKUP_OBJECT (gestion_election, rech2_gest_elec_entry, "rech2_gest_elec_entry");
  GLADE_HOOKUP_OBJECT (gestion_election, rech1_gest_elec_button, "rech1_gest_elec_button");
  GLADE_HOOKUP_OBJECT (gestion_election, supp_gest_elec_button, "supp_gest_elec_button");
  GLADE_HOOKUP_OBJECT (gestion_election, alignment237, "alignment237");
  GLADE_HOOKUP_OBJECT (gestion_election, hbox237, "hbox237");
  GLADE_HOOKUP_OBJECT (gestion_election, image268, "image268");
  GLADE_HOOKUP_OBJECT (gestion_election, label888, "label888");
  GLADE_HOOKUP_OBJECT (gestion_election, ajout_gest_elec_button, "ajout_gest_elec_button");
  GLADE_HOOKUP_OBJECT (gestion_election, alignment236, "alignment236");
  GLADE_HOOKUP_OBJECT (gestion_election, hbox236, "hbox236");
  GLADE_HOOKUP_OBJECT (gestion_election, image267, "image267");
  GLADE_HOOKUP_OBJECT (gestion_election, label887, "label887");
  GLADE_HOOKUP_OBJECT (gestion_election, modif_gest_elec_button, "modif_gest_elec_button");
  GLADE_HOOKUP_OBJECT (gestion_election, alignment235, "alignment235");
  GLADE_HOOKUP_OBJECT (gestion_election, hbox235, "hbox235");
  GLADE_HOOKUP_OBJECT (gestion_election, image266, "image266");
  GLADE_HOOKUP_OBJECT (gestion_election, label886, "label886");
  GLADE_HOOKUP_OBJECT (gestion_election, rech2_gest_elec_button, "rech2_gest_elec_button");

  return gestion_election;
}

GtkWidget*
create_ajout_election_ (void)
{
  GtkWidget *ajout_election_;
  GtkWidget *fixed79;
  GtkWidget *nbrh_ajou_elec_entry;
  GtkObject *nbrc_ajou_elec_entry_adj;
  GtkWidget *nbrc_ajou_elec_entry;
  GtkWidget *button282;
  GtkWidget *alignment212;
  GtkWidget *hbox212;
  GtkWidget *image241;
  GtkWidget *label849;
  GtkWidget *button283;
  GtkWidget *alignment213;
  GtkWidget *hbox213;
  GtkWidget *image242;
  GtkWidget *label850;
  GtkWidget *button284;
  GtkWidget *alignment214;
  GtkWidget *hbox214;
  GtkWidget *image243;
  GtkWidget *label851;
  GtkWidget *button285;
  GtkWidget *alignment215;
  GtkWidget *hbox215;
  GtkWidget *image244;
  GtkWidget *label852;
  GtkWidget *image247;
  GtkObject *jdate_ajou_elec_entry_adj;
  GtkWidget *jdate_ajou_elec_entry;
  GtkObject *mdate_ajou_elec_entry_adj;
  GtkWidget *mdate_ajou_elec_entry;
  GtkObject *adate_ajou_elec_entry_adj;
  GtkWidget *adate_ajou_elec_entry;
  GtkWidget *date_ajou_elec_label;
  GtkWidget *nbrc_ajou_elec_label;
  GtkWidget *nbrh_ajou_elec_label;
  GtkWidget *muni_ajou_elec_label;
  GtkWidget *id_ajou_elec_entry;
  GtkWidget *id_ajou_elec_label;
  GtkWidget *val_ajou_elec_button;
  GtkWidget *alignment217;
  GtkWidget *hbox217;
  GtkWidget *image246;
  GtkWidget *label854;
  GtkWidget *muni_ajou_elec_entry;
  GtkWidget *ann_ajou_elec_button;
  GtkWidget *alignment216;
  GtkWidget *hbox216;
  GtkWidget *image245;
  GtkWidget *label853;
  GtkWidget *label855;
  GtkWidget *prcd_ajout_elec;
  GtkWidget *alignment211;
  GtkWidget *hbox211;
  GtkWidget *image240;
  GtkWidget *label848;
  GtkWidget *labelajout;

  ajout_election_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_election_), _("ajout election "));

  fixed79 = gtk_fixed_new ();
  gtk_widget_show (fixed79);
  gtk_container_add (GTK_CONTAINER (ajout_election_), fixed79);

  nbrh_ajou_elec_entry = gtk_entry_new ();
  gtk_widget_show (nbrh_ajou_elec_entry);
  gtk_fixed_put (GTK_FIXED (fixed79), nbrh_ajou_elec_entry, 600, 480);
  gtk_widget_set_size_request (nbrh_ajou_elec_entry, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (nbrh_ajou_elec_entry), 8226);

  nbrc_ajou_elec_entry_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  nbrc_ajou_elec_entry = gtk_spin_button_new (GTK_ADJUSTMENT (nbrc_ajou_elec_entry_adj), 1, 0);
  gtk_widget_show (nbrc_ajou_elec_entry);
  gtk_fixed_put (GTK_FIXED (fixed79), nbrc_ajou_elec_entry, 840, 480);
  gtk_widget_set_size_request (nbrc_ajou_elec_entry, 155, 28);

  button282 = gtk_button_new ();
  gtk_widget_show (button282);
  gtk_fixed_put (GTK_FIXED (fixed79), button282, 920, 32);
  gtk_widget_set_size_request (button282, 160, 40);

  alignment212 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment212);
  gtk_container_add (GTK_CONTAINER (button282), alignment212);

  hbox212 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox212);
  gtk_container_add (GTK_CONTAINER (alignment212), hbox212);

  image241 = gtk_image_new_from_stock ("gtk-connect", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image241);
  gtk_box_pack_start (GTK_BOX (hbox212), image241, FALSE, FALSE, 0);

  label849 = gtk_label_new_with_mnemonic (_("Se deconnecter "));
  gtk_widget_show (label849);
  gtk_box_pack_start (GTK_BOX (hbox212), label849, FALSE, FALSE, 0);

  button283 = gtk_button_new ();
  gtk_widget_show (button283);
  gtk_fixed_put (GTK_FIXED (fixed79), button283, 736, 32);
  gtk_widget_set_size_request (button283, 152, 40);

  alignment213 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment213);
  gtk_container_add (GTK_CONTAINER (button283), alignment213);

  hbox213 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox213);
  gtk_container_add (GTK_CONTAINER (alignment213), hbox213);

  image242 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image242);
  gtk_box_pack_start (GTK_BOX (hbox213), image242, FALSE, FALSE, 0);

  label850 = gtk_label_new_with_mnemonic (_("profile"));
  gtk_widget_show (label850);
  gtk_box_pack_start (GTK_BOX (hbox213), label850, FALSE, FALSE, 0);

  button284 = gtk_button_new ();
  gtk_widget_show (button284);
  gtk_fixed_put (GTK_FIXED (fixed79), button284, 568, 32);
  gtk_widget_set_size_request (button284, 144, 40);

  alignment214 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment214);
  gtk_container_add (GTK_CONTAINER (button284), alignment214);

  hbox214 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox214);
  gtk_container_add (GTK_CONTAINER (alignment214), hbox214);

  image243 = gtk_image_new_from_stock ("gtk-page-setup", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image243);
  gtk_box_pack_start (GTK_BOX (hbox214), image243, FALSE, FALSE, 0);

  label851 = gtk_label_new_with_mnemonic (_("administration"));
  gtk_widget_show (label851);
  gtk_box_pack_start (GTK_BOX (hbox214), label851, FALSE, FALSE, 0);

  button285 = gtk_button_new ();
  gtk_widget_show (button285);
  gtk_fixed_put (GTK_FIXED (fixed79), button285, 32, 24);
  gtk_widget_set_size_request (button285, 136, 40);

  alignment215 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment215);
  gtk_container_add (GTK_CONTAINER (button285), alignment215);

  hbox215 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox215);
  gtk_container_add (GTK_CONTAINER (alignment215), hbox215);

  image244 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image244);
  gtk_box_pack_start (GTK_BOX (hbox215), image244, FALSE, FALSE, 0);

  label852 = gtk_label_new_with_mnemonic (_("accueil"));
  gtk_widget_show (label852);
  gtk_box_pack_start (GTK_BOX (hbox215), label852, FALSE, FALSE, 0);

  image247 = create_pixmap (ajout_election_, "313276975_3588004334761330_8207675648328059895_n.jpg");
  gtk_widget_show (image247);
  gtk_fixed_put (GTK_FIXED (fixed79), image247, 400, 192);
  gtk_widget_set_size_request (image247, 408, 224);

  jdate_ajou_elec_entry_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jdate_ajou_elec_entry = gtk_spin_button_new (GTK_ADJUSTMENT (jdate_ajou_elec_entry_adj), 1, 0);
  gtk_widget_show (jdate_ajou_elec_entry);
  gtk_fixed_put (GTK_FIXED (fixed79), jdate_ajou_elec_entry, 1024, 480);
  gtk_widget_set_size_request (jdate_ajou_elec_entry, 60, 27);

  mdate_ajou_elec_entry_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mdate_ajou_elec_entry = gtk_spin_button_new (GTK_ADJUSTMENT (mdate_ajou_elec_entry_adj), 1, 0);
  gtk_widget_show (mdate_ajou_elec_entry);
  gtk_fixed_put (GTK_FIXED (fixed79), mdate_ajou_elec_entry, 1096, 480);
  gtk_widget_set_size_request (mdate_ajou_elec_entry, 60, 27);

  adate_ajou_elec_entry_adj = gtk_adjustment_new (1, 2020, 2030, 1, 10, 10);
  adate_ajou_elec_entry = gtk_spin_button_new (GTK_ADJUSTMENT (adate_ajou_elec_entry_adj), 1, 0);
  gtk_widget_show (adate_ajou_elec_entry);
  gtk_fixed_put (GTK_FIXED (fixed79), adate_ajou_elec_entry, 1160, 480);
  gtk_widget_set_size_request (adate_ajou_elec_entry, 60, 27);

  date_ajou_elec_label = gtk_label_new (_("date d'election "));
  gtk_widget_show (date_ajou_elec_label);
  gtk_fixed_put (GTK_FIXED (fixed79), date_ajou_elec_label, 1008, 456);
  gtk_widget_set_size_request (date_ajou_elec_label, 200, 24);

  nbrc_ajou_elec_label = gtk_label_new (_("nombre de conseilliers"));
  gtk_widget_show (nbrc_ajou_elec_label);
  gtk_fixed_put (GTK_FIXED (fixed79), nbrc_ajou_elec_label, 808, 448);
  gtk_widget_set_size_request (nbrc_ajou_elec_label, 224, 32);

  nbrh_ajou_elec_label = gtk_label_new (_("nombre d'habitants"));
  gtk_widget_show (nbrh_ajou_elec_label);
  gtk_fixed_put (GTK_FIXED (fixed79), nbrh_ajou_elec_label, 592, 448);
  gtk_widget_set_size_request (nbrh_ajou_elec_label, 184, 32);

  muni_ajou_elec_label = gtk_label_new (_("nom de la municiplait\303\251"));
  gtk_widget_show (muni_ajou_elec_label);
  gtk_fixed_put (GTK_FIXED (fixed79), muni_ajou_elec_label, 272, 448);
  gtk_widget_set_size_request (muni_ajou_elec_label, 208, 32);

  id_ajou_elec_entry = gtk_entry_new ();
  gtk_widget_show (id_ajou_elec_entry);
  gtk_fixed_put (GTK_FIXED (fixed79), id_ajou_elec_entry, 40, 480);
  gtk_widget_set_size_request (id_ajou_elec_entry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_ajou_elec_entry), 8226);

  id_ajou_elec_label = gtk_label_new (_("id"));
  gtk_widget_show (id_ajou_elec_label);
  gtk_fixed_put (GTK_FIXED (fixed79), id_ajou_elec_label, 64, 456);
  gtk_widget_set_size_request (id_ajou_elec_label, 88, 16);

  val_ajou_elec_button = gtk_button_new ();
  gtk_widget_show (val_ajou_elec_button);
  gtk_fixed_put (GTK_FIXED (fixed79), val_ajou_elec_button, 592, 568);
  gtk_widget_set_size_request (val_ajou_elec_button, 208, 40);

  alignment217 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment217);
  gtk_container_add (GTK_CONTAINER (val_ajou_elec_button), alignment217);

  hbox217 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox217);
  gtk_container_add (GTK_CONTAINER (alignment217), hbox217);

  image246 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image246);
  gtk_box_pack_start (GTK_BOX (hbox217), image246, FALSE, FALSE, 0);

  label854 = gtk_label_new_with_mnemonic (_("valider "));
  gtk_widget_show (label854);
  gtk_box_pack_start (GTK_BOX (hbox217), label854, FALSE, FALSE, 0);

  muni_ajou_elec_entry = gtk_combo_box_entry_new_text ();
  gtk_widget_show (muni_ajou_elec_entry);
  gtk_fixed_put (GTK_FIXED (fixed79), muni_ajou_elec_entry, 272, 480);
  gtk_widget_set_size_request (muni_ajou_elec_entry, 231, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (muni_ajou_elec_entry), _("ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (muni_ajou_elec_entry), _("tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (muni_ajou_elec_entry), _("manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (muni_ajou_elec_entry), _("monastir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (muni_ajou_elec_entry), _("sousse"));

  ann_ajou_elec_button = gtk_button_new ();
  gtk_widget_show (ann_ajou_elec_button);
  gtk_fixed_put (GTK_FIXED (fixed79), ann_ajou_elec_button, 344, 568);
  gtk_widget_set_size_request (ann_ajou_elec_button, 208, 40);

  alignment216 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment216);
  gtk_container_add (GTK_CONTAINER (ann_ajou_elec_button), alignment216);

  hbox216 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox216);
  gtk_container_add (GTK_CONTAINER (alignment216), hbox216);

  image245 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image245);
  gtk_box_pack_start (GTK_BOX (hbox216), image245, FALSE, FALSE, 0);

  label853 = gtk_label_new_with_mnemonic (_("annuler "));
  gtk_widget_show (label853);
  gtk_box_pack_start (GTK_BOX (hbox216), label853, FALSE, FALSE, 0);

  label855 = gtk_label_new (_("nouvelle  election "));
  gtk_widget_show (label855);
  gtk_fixed_put (GTK_FIXED (fixed79), label855, 384, 144);
  gtk_widget_set_size_request (label855, 424, 24);

  prcd_ajout_elec = gtk_button_new ();
  gtk_widget_show (prcd_ajout_elec);
  gtk_fixed_put (GTK_FIXED (fixed79), prcd_ajout_elec, 8, 96);
  gtk_widget_set_size_request (prcd_ajout_elec, 184, 32);

  alignment211 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment211);
  gtk_container_add (GTK_CONTAINER (prcd_ajout_elec), alignment211);

  hbox211 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox211);
  gtk_container_add (GTK_CONTAINER (alignment211), hbox211);

  image240 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image240);
  gtk_box_pack_start (GTK_BOX (hbox211), image240, FALSE, FALSE, 0);

  label848 = gtk_label_new_with_mnemonic (_("precedent "));
  gtk_widget_show (label848);
  gtk_box_pack_start (GTK_BOX (hbox211), label848, FALSE, FALSE, 0);

  labelajout = gtk_label_new ("");
  gtk_widget_show (labelajout);
  gtk_fixed_put (GTK_FIXED (fixed79), labelajout, 888, 536);
  gtk_widget_set_size_request (labelajout, 360, 56);

  g_signal_connect ((gpointer) val_ajou_elec_button, "clicked",
                    G_CALLBACK (on_val_ajou_elec_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) ann_ajou_elec_button, "clicked",
                    G_CALLBACK (on_ann_ajou_elec_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) prcd_ajout_elec, "clicked",
                    G_CALLBACK (on_prcd_ajout_elec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_election_, ajout_election_, "ajout_election_");
  GLADE_HOOKUP_OBJECT (ajout_election_, fixed79, "fixed79");
  GLADE_HOOKUP_OBJECT (ajout_election_, nbrh_ajou_elec_entry, "nbrh_ajou_elec_entry");
  GLADE_HOOKUP_OBJECT (ajout_election_, nbrc_ajou_elec_entry, "nbrc_ajou_elec_entry");
  GLADE_HOOKUP_OBJECT (ajout_election_, button282, "button282");
  GLADE_HOOKUP_OBJECT (ajout_election_, alignment212, "alignment212");
  GLADE_HOOKUP_OBJECT (ajout_election_, hbox212, "hbox212");
  GLADE_HOOKUP_OBJECT (ajout_election_, image241, "image241");
  GLADE_HOOKUP_OBJECT (ajout_election_, label849, "label849");
  GLADE_HOOKUP_OBJECT (ajout_election_, button283, "button283");
  GLADE_HOOKUP_OBJECT (ajout_election_, alignment213, "alignment213");
  GLADE_HOOKUP_OBJECT (ajout_election_, hbox213, "hbox213");
  GLADE_HOOKUP_OBJECT (ajout_election_, image242, "image242");
  GLADE_HOOKUP_OBJECT (ajout_election_, label850, "label850");
  GLADE_HOOKUP_OBJECT (ajout_election_, button284, "button284");
  GLADE_HOOKUP_OBJECT (ajout_election_, alignment214, "alignment214");
  GLADE_HOOKUP_OBJECT (ajout_election_, hbox214, "hbox214");
  GLADE_HOOKUP_OBJECT (ajout_election_, image243, "image243");
  GLADE_HOOKUP_OBJECT (ajout_election_, label851, "label851");
  GLADE_HOOKUP_OBJECT (ajout_election_, button285, "button285");
  GLADE_HOOKUP_OBJECT (ajout_election_, alignment215, "alignment215");
  GLADE_HOOKUP_OBJECT (ajout_election_, hbox215, "hbox215");
  GLADE_HOOKUP_OBJECT (ajout_election_, image244, "image244");
  GLADE_HOOKUP_OBJECT (ajout_election_, label852, "label852");
  GLADE_HOOKUP_OBJECT (ajout_election_, image247, "image247");
  GLADE_HOOKUP_OBJECT (ajout_election_, jdate_ajou_elec_entry, "jdate_ajou_elec_entry");
  GLADE_HOOKUP_OBJECT (ajout_election_, mdate_ajou_elec_entry, "mdate_ajou_elec_entry");
  GLADE_HOOKUP_OBJECT (ajout_election_, adate_ajou_elec_entry, "adate_ajou_elec_entry");
  GLADE_HOOKUP_OBJECT (ajout_election_, date_ajou_elec_label, "date_ajou_elec_label");
  GLADE_HOOKUP_OBJECT (ajout_election_, nbrc_ajou_elec_label, "nbrc_ajou_elec_label");
  GLADE_HOOKUP_OBJECT (ajout_election_, nbrh_ajou_elec_label, "nbrh_ajou_elec_label");
  GLADE_HOOKUP_OBJECT (ajout_election_, muni_ajou_elec_label, "muni_ajou_elec_label");
  GLADE_HOOKUP_OBJECT (ajout_election_, id_ajou_elec_entry, "id_ajou_elec_entry");
  GLADE_HOOKUP_OBJECT (ajout_election_, id_ajou_elec_label, "id_ajou_elec_label");
  GLADE_HOOKUP_OBJECT (ajout_election_, val_ajou_elec_button, "val_ajou_elec_button");
  GLADE_HOOKUP_OBJECT (ajout_election_, alignment217, "alignment217");
  GLADE_HOOKUP_OBJECT (ajout_election_, hbox217, "hbox217");
  GLADE_HOOKUP_OBJECT (ajout_election_, image246, "image246");
  GLADE_HOOKUP_OBJECT (ajout_election_, label854, "label854");
  GLADE_HOOKUP_OBJECT (ajout_election_, muni_ajou_elec_entry, "muni_ajou_elec_entry");
  GLADE_HOOKUP_OBJECT (ajout_election_, ann_ajou_elec_button, "ann_ajou_elec_button");
  GLADE_HOOKUP_OBJECT (ajout_election_, alignment216, "alignment216");
  GLADE_HOOKUP_OBJECT (ajout_election_, hbox216, "hbox216");
  GLADE_HOOKUP_OBJECT (ajout_election_, image245, "image245");
  GLADE_HOOKUP_OBJECT (ajout_election_, label853, "label853");
  GLADE_HOOKUP_OBJECT (ajout_election_, label855, "label855");
  GLADE_HOOKUP_OBJECT (ajout_election_, prcd_ajout_elec, "prcd_ajout_elec");
  GLADE_HOOKUP_OBJECT (ajout_election_, alignment211, "alignment211");
  GLADE_HOOKUP_OBJECT (ajout_election_, hbox211, "hbox211");
  GLADE_HOOKUP_OBJECT (ajout_election_, image240, "image240");
  GLADE_HOOKUP_OBJECT (ajout_election_, label848, "label848");
  GLADE_HOOKUP_OBJECT (ajout_election_, labelajout, "labelajout");

  return ajout_election_;
}

GtkWidget*
create_modif_election_ (void)
{
  GtkWidget *modif_election_;
  GtkWidget *fixed81;
  GtkWidget *muni_modi_elec_entry;
  GtkObject *nbrc_modi_elec_spin_adj;
  GtkWidget *nbrc_modi_elec_spin;
  GtkWidget *button293;
  GtkWidget *alignment223;
  GtkWidget *hbox223;
  GtkWidget *image253;
  GtkWidget *label870;
  GtkWidget *button294;
  GtkWidget *alignment224;
  GtkWidget *hbox224;
  GtkWidget *image254;
  GtkWidget *label871;
  GtkWidget *button295;
  GtkWidget *alignment225;
  GtkWidget *hbox225;
  GtkWidget *image255;
  GtkWidget *label872;
  GtkWidget *button296;
  GtkWidget *alignment226;
  GtkWidget *hbox226;
  GtkWidget *image256;
  GtkWidget *label873;
  GtkWidget *image259;
  GtkWidget *label876;
  GtkObject *jdate_modi_elec_spin_adj;
  GtkWidget *jdate_modi_elec_spin;
  GtkObject *mdate_modi_elec_spin_adj;
  GtkWidget *mdate_modi_elec_spin;
  GtkObject *adate_modi_elec_spin_adj;
  GtkWidget *adate_modi_elec_spin;
  GtkWidget *ann_modi_elec_button;
  GtkWidget *alignment227;
  GtkWidget *hbox227;
  GtkWidget *image257;
  GtkWidget *label874;
  GtkWidget *val_modi_elec_button;
  GtkWidget *alignment228;
  GtkWidget *hbox228;
  GtkWidget *image258;
  GtkWidget *label875;
  GtkWidget *date_modi_elec_label;
  GtkWidget *nbrc_modi_elec_label;
  GtkWidget *nbrh_modi_elec_label;
  GtkWidget *id_modif_elec_entry;
  GtkWidget *id_modif_elec_label;
  GtkWidget *prcd_modif_elec;
  GtkWidget *alignment222;
  GtkWidget *hbox222;
  GtkWidget *image252;
  GtkWidget *label869;
  GtkWidget *labelmodif;
  GtkWidget *muni_modi_elec_combobox;
  GtkWidget *muni_modi_elec_label;

  modif_election_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modif_election_), _("modif election "));

  fixed81 = gtk_fixed_new ();
  gtk_widget_show (fixed81);
  gtk_container_add (GTK_CONTAINER (modif_election_), fixed81);

  muni_modi_elec_entry = gtk_entry_new ();
  gtk_widget_show (muni_modi_elec_entry);
  gtk_fixed_put (GTK_FIXED (fixed81), muni_modi_elec_entry, 520, 480);
  gtk_widget_set_size_request (muni_modi_elec_entry, 208, 32);
  gtk_entry_set_text (GTK_ENTRY (muni_modi_elec_entry), _("50000"));
  gtk_entry_set_invisible_char (GTK_ENTRY (muni_modi_elec_entry), 8226);

  nbrc_modi_elec_spin_adj = gtk_adjustment_new (1, 0, 20, 1, 10, 10);
  nbrc_modi_elec_spin = gtk_spin_button_new (GTK_ADJUSTMENT (nbrc_modi_elec_spin_adj), 1, 0);
  gtk_widget_show (nbrc_modi_elec_spin);
  gtk_fixed_put (GTK_FIXED (fixed81), nbrc_modi_elec_spin, 792, 488);
  gtk_widget_set_size_request (nbrc_modi_elec_spin, 155, 28);

  button293 = gtk_button_new ();
  gtk_widget_show (button293);
  gtk_fixed_put (GTK_FIXED (fixed81), button293, 920, 32);
  gtk_widget_set_size_request (button293, 160, 40);

  alignment223 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment223);
  gtk_container_add (GTK_CONTAINER (button293), alignment223);

  hbox223 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox223);
  gtk_container_add (GTK_CONTAINER (alignment223), hbox223);

  image253 = gtk_image_new_from_stock ("gtk-connect", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image253);
  gtk_box_pack_start (GTK_BOX (hbox223), image253, FALSE, FALSE, 0);

  label870 = gtk_label_new_with_mnemonic (_("Se deconnecter "));
  gtk_widget_show (label870);
  gtk_box_pack_start (GTK_BOX (hbox223), label870, FALSE, FALSE, 0);

  button294 = gtk_button_new ();
  gtk_widget_show (button294);
  gtk_fixed_put (GTK_FIXED (fixed81), button294, 736, 32);
  gtk_widget_set_size_request (button294, 152, 40);

  alignment224 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment224);
  gtk_container_add (GTK_CONTAINER (button294), alignment224);

  hbox224 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox224);
  gtk_container_add (GTK_CONTAINER (alignment224), hbox224);

  image254 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image254);
  gtk_box_pack_start (GTK_BOX (hbox224), image254, FALSE, FALSE, 0);

  label871 = gtk_label_new_with_mnemonic (_("profile"));
  gtk_widget_show (label871);
  gtk_box_pack_start (GTK_BOX (hbox224), label871, FALSE, FALSE, 0);

  button295 = gtk_button_new ();
  gtk_widget_show (button295);
  gtk_fixed_put (GTK_FIXED (fixed81), button295, 568, 32);
  gtk_widget_set_size_request (button295, 144, 40);

  alignment225 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment225);
  gtk_container_add (GTK_CONTAINER (button295), alignment225);

  hbox225 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox225);
  gtk_container_add (GTK_CONTAINER (alignment225), hbox225);

  image255 = gtk_image_new_from_stock ("gtk-page-setup", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image255);
  gtk_box_pack_start (GTK_BOX (hbox225), image255, FALSE, FALSE, 0);

  label872 = gtk_label_new_with_mnemonic (_("administration"));
  gtk_widget_show (label872);
  gtk_box_pack_start (GTK_BOX (hbox225), label872, FALSE, FALSE, 0);

  button296 = gtk_button_new ();
  gtk_widget_show (button296);
  gtk_fixed_put (GTK_FIXED (fixed81), button296, 32, 24);
  gtk_widget_set_size_request (button296, 136, 40);

  alignment226 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment226);
  gtk_container_add (GTK_CONTAINER (button296), alignment226);

  hbox226 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox226);
  gtk_container_add (GTK_CONTAINER (alignment226), hbox226);

  image256 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image256);
  gtk_box_pack_start (GTK_BOX (hbox226), image256, FALSE, FALSE, 0);

  label873 = gtk_label_new_with_mnemonic (_("accueil"));
  gtk_widget_show (label873);
  gtk_box_pack_start (GTK_BOX (hbox226), label873, FALSE, FALSE, 0);

  image259 = create_pixmap (modif_election_, "313276975_3588004334761330_8207675648328059895_n.jpg");
  gtk_widget_show (image259);
  gtk_fixed_put (GTK_FIXED (fixed81), image259, 400, 192);
  gtk_widget_set_size_request (image259, 408, 224);

  label876 = gtk_label_new (_("instances superieure independantes pour les  elections "));
  gtk_widget_show (label876);
  gtk_fixed_put (GTK_FIXED (fixed81), label876, 384, 144);
  gtk_widget_set_size_request (label876, 424, 24);

  jdate_modi_elec_spin_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  jdate_modi_elec_spin = gtk_spin_button_new (GTK_ADJUSTMENT (jdate_modi_elec_spin_adj), 1, 0);
  gtk_widget_show (jdate_modi_elec_spin);
  gtk_fixed_put (GTK_FIXED (fixed81), jdate_modi_elec_spin, 1016, 488);
  gtk_widget_set_size_request (jdate_modi_elec_spin, 60, 27);

  mdate_modi_elec_spin_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  mdate_modi_elec_spin = gtk_spin_button_new (GTK_ADJUSTMENT (mdate_modi_elec_spin_adj), 1, 0);
  gtk_widget_show (mdate_modi_elec_spin);
  gtk_fixed_put (GTK_FIXED (fixed81), mdate_modi_elec_spin, 1096, 488);
  gtk_widget_set_size_request (mdate_modi_elec_spin, 60, 27);

  adate_modi_elec_spin_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  adate_modi_elec_spin = gtk_spin_button_new (GTK_ADJUSTMENT (adate_modi_elec_spin_adj), 1, 0);
  gtk_widget_show (adate_modi_elec_spin);
  gtk_fixed_put (GTK_FIXED (fixed81), adate_modi_elec_spin, 1168, 488);
  gtk_widget_set_size_request (adate_modi_elec_spin, 60, 27);

  ann_modi_elec_button = gtk_button_new ();
  gtk_widget_show (ann_modi_elec_button);
  gtk_fixed_put (GTK_FIXED (fixed81), ann_modi_elec_button, 344, 568);
  gtk_widget_set_size_request (ann_modi_elec_button, 208, 40);

  alignment227 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment227);
  gtk_container_add (GTK_CONTAINER (ann_modi_elec_button), alignment227);

  hbox227 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox227);
  gtk_container_add (GTK_CONTAINER (alignment227), hbox227);

  image257 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image257);
  gtk_box_pack_start (GTK_BOX (hbox227), image257, FALSE, FALSE, 0);

  label874 = gtk_label_new_with_mnemonic (_("annuler "));
  gtk_widget_show (label874);
  gtk_box_pack_start (GTK_BOX (hbox227), label874, FALSE, FALSE, 0);

  val_modi_elec_button = gtk_button_new ();
  gtk_widget_show (val_modi_elec_button);
  gtk_fixed_put (GTK_FIXED (fixed81), val_modi_elec_button, 592, 568);
  gtk_widget_set_size_request (val_modi_elec_button, 208, 40);

  alignment228 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment228);
  gtk_container_add (GTK_CONTAINER (val_modi_elec_button), alignment228);

  hbox228 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox228);
  gtk_container_add (GTK_CONTAINER (alignment228), hbox228);

  image258 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image258);
  gtk_box_pack_start (GTK_BOX (hbox228), image258, FALSE, FALSE, 0);

  label875 = gtk_label_new_with_mnemonic (_("valider "));
  gtk_widget_show (label875);
  gtk_box_pack_start (GTK_BOX (hbox228), label875, FALSE, FALSE, 0);

  date_modi_elec_label = gtk_label_new (_("date d'election "));
  gtk_widget_show (date_modi_elec_label);
  gtk_fixed_put (GTK_FIXED (fixed81), date_modi_elec_label, 1016, 456);
  gtk_widget_set_size_request (date_modi_elec_label, 200, 24);

  nbrc_modi_elec_label = gtk_label_new (_("nombre de conseilliers"));
  gtk_widget_show (nbrc_modi_elec_label);
  gtk_fixed_put (GTK_FIXED (fixed81), nbrc_modi_elec_label, 728, 456);
  gtk_widget_set_size_request (nbrc_modi_elec_label, 264, 24);

  nbrh_modi_elec_label = gtk_label_new (_("nombre d'habitants"));
  gtk_widget_show (nbrh_modi_elec_label);
  gtk_fixed_put (GTK_FIXED (fixed81), nbrh_modi_elec_label, 520, 448);
  gtk_widget_set_size_request (nbrh_modi_elec_label, 184, 32);

  id_modif_elec_entry = gtk_entry_new ();
  gtk_widget_show (id_modif_elec_entry);
  gtk_fixed_put (GTK_FIXED (fixed81), id_modif_elec_entry, 32, 480);
  gtk_widget_set_size_request (id_modif_elec_entry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_modif_elec_entry), 8226);

  id_modif_elec_label = gtk_label_new (_("id"));
  gtk_widget_show (id_modif_elec_label);
  gtk_fixed_put (GTK_FIXED (fixed81), id_modif_elec_label, 56, 448);
  gtk_widget_set_size_request (id_modif_elec_label, 57, 17);

  prcd_modif_elec = gtk_button_new ();
  gtk_widget_show (prcd_modif_elec);
  gtk_fixed_put (GTK_FIXED (fixed81), prcd_modif_elec, 8, 96);
  gtk_widget_set_size_request (prcd_modif_elec, 184, 32);

  alignment222 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment222);
  gtk_container_add (GTK_CONTAINER (prcd_modif_elec), alignment222);

  hbox222 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox222);
  gtk_container_add (GTK_CONTAINER (alignment222), hbox222);

  image252 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image252);
  gtk_box_pack_start (GTK_BOX (hbox222), image252, FALSE, FALSE, 0);

  label869 = gtk_label_new_with_mnemonic (_("precedent "));
  gtk_widget_show (label869);
  gtk_box_pack_start (GTK_BOX (hbox222), label869, FALSE, FALSE, 0);

  labelmodif = gtk_label_new ("");
  gtk_widget_show (labelmodif);
  gtk_fixed_put (GTK_FIXED (fixed81), labelmodif, 840, 536);
  gtk_widget_set_size_request (labelmodif, 384, 56);

  muni_modi_elec_combobox = gtk_combo_box_entry_new_text ();
  gtk_widget_show (muni_modi_elec_combobox);
  gtk_fixed_put (GTK_FIXED (fixed81), muni_modi_elec_combobox, 224, 480);
  gtk_widget_set_size_request (muni_modi_elec_combobox, 231, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (muni_modi_elec_combobox), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (muni_modi_elec_combobox), _("ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (muni_modi_elec_combobox), _("manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (muni_modi_elec_combobox), _("sousse "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (muni_modi_elec_combobox), _("monastir"));

  muni_modi_elec_label = gtk_label_new (_("nom de la municipalit\303\251"));
  gtk_widget_show (muni_modi_elec_label);
  gtk_fixed_put (GTK_FIXED (fixed81), muni_modi_elec_label, 240, 440);
  gtk_widget_set_size_request (muni_modi_elec_label, 208, 32);

  g_signal_connect ((gpointer) ann_modi_elec_button, "clicked",
                    G_CALLBACK (on_ann_modi_elec_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) val_modi_elec_button, "clicked",
                    G_CALLBACK (on_val_modi_elec_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) prcd_modif_elec, "clicked",
                    G_CALLBACK (on_prcd_modif_elec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modif_election_, modif_election_, "modif_election_");
  GLADE_HOOKUP_OBJECT (modif_election_, fixed81, "fixed81");
  GLADE_HOOKUP_OBJECT (modif_election_, muni_modi_elec_entry, "muni_modi_elec_entry");
  GLADE_HOOKUP_OBJECT (modif_election_, nbrc_modi_elec_spin, "nbrc_modi_elec_spin");
  GLADE_HOOKUP_OBJECT (modif_election_, button293, "button293");
  GLADE_HOOKUP_OBJECT (modif_election_, alignment223, "alignment223");
  GLADE_HOOKUP_OBJECT (modif_election_, hbox223, "hbox223");
  GLADE_HOOKUP_OBJECT (modif_election_, image253, "image253");
  GLADE_HOOKUP_OBJECT (modif_election_, label870, "label870");
  GLADE_HOOKUP_OBJECT (modif_election_, button294, "button294");
  GLADE_HOOKUP_OBJECT (modif_election_, alignment224, "alignment224");
  GLADE_HOOKUP_OBJECT (modif_election_, hbox224, "hbox224");
  GLADE_HOOKUP_OBJECT (modif_election_, image254, "image254");
  GLADE_HOOKUP_OBJECT (modif_election_, label871, "label871");
  GLADE_HOOKUP_OBJECT (modif_election_, button295, "button295");
  GLADE_HOOKUP_OBJECT (modif_election_, alignment225, "alignment225");
  GLADE_HOOKUP_OBJECT (modif_election_, hbox225, "hbox225");
  GLADE_HOOKUP_OBJECT (modif_election_, image255, "image255");
  GLADE_HOOKUP_OBJECT (modif_election_, label872, "label872");
  GLADE_HOOKUP_OBJECT (modif_election_, button296, "button296");
  GLADE_HOOKUP_OBJECT (modif_election_, alignment226, "alignment226");
  GLADE_HOOKUP_OBJECT (modif_election_, hbox226, "hbox226");
  GLADE_HOOKUP_OBJECT (modif_election_, image256, "image256");
  GLADE_HOOKUP_OBJECT (modif_election_, label873, "label873");
  GLADE_HOOKUP_OBJECT (modif_election_, image259, "image259");
  GLADE_HOOKUP_OBJECT (modif_election_, label876, "label876");
  GLADE_HOOKUP_OBJECT (modif_election_, jdate_modi_elec_spin, "jdate_modi_elec_spin");
  GLADE_HOOKUP_OBJECT (modif_election_, mdate_modi_elec_spin, "mdate_modi_elec_spin");
  GLADE_HOOKUP_OBJECT (modif_election_, adate_modi_elec_spin, "adate_modi_elec_spin");
  GLADE_HOOKUP_OBJECT (modif_election_, ann_modi_elec_button, "ann_modi_elec_button");
  GLADE_HOOKUP_OBJECT (modif_election_, alignment227, "alignment227");
  GLADE_HOOKUP_OBJECT (modif_election_, hbox227, "hbox227");
  GLADE_HOOKUP_OBJECT (modif_election_, image257, "image257");
  GLADE_HOOKUP_OBJECT (modif_election_, label874, "label874");
  GLADE_HOOKUP_OBJECT (modif_election_, val_modi_elec_button, "val_modi_elec_button");
  GLADE_HOOKUP_OBJECT (modif_election_, alignment228, "alignment228");
  GLADE_HOOKUP_OBJECT (modif_election_, hbox228, "hbox228");
  GLADE_HOOKUP_OBJECT (modif_election_, image258, "image258");
  GLADE_HOOKUP_OBJECT (modif_election_, label875, "label875");
  GLADE_HOOKUP_OBJECT (modif_election_, date_modi_elec_label, "date_modi_elec_label");
  GLADE_HOOKUP_OBJECT (modif_election_, nbrc_modi_elec_label, "nbrc_modi_elec_label");
  GLADE_HOOKUP_OBJECT (modif_election_, nbrh_modi_elec_label, "nbrh_modi_elec_label");
  GLADE_HOOKUP_OBJECT (modif_election_, id_modif_elec_entry, "id_modif_elec_entry");
  GLADE_HOOKUP_OBJECT (modif_election_, id_modif_elec_label, "id_modif_elec_label");
  GLADE_HOOKUP_OBJECT (modif_election_, prcd_modif_elec, "prcd_modif_elec");
  GLADE_HOOKUP_OBJECT (modif_election_, alignment222, "alignment222");
  GLADE_HOOKUP_OBJECT (modif_election_, hbox222, "hbox222");
  GLADE_HOOKUP_OBJECT (modif_election_, image252, "image252");
  GLADE_HOOKUP_OBJECT (modif_election_, label869, "label869");
  GLADE_HOOKUP_OBJECT (modif_election_, labelmodif, "labelmodif");
  GLADE_HOOKUP_OBJECT (modif_election_, muni_modi_elec_combobox, "muni_modi_elec_combobox");
  GLADE_HOOKUP_OBJECT (modif_election_, muni_modi_elec_label, "muni_modi_elec_label");

  return modif_election_;
}

GtkWidget*
create_supprimer_election_ (void)
{
  GtkWidget *supprimer_election_;
  GtkWidget *fixed82;
  GtkWidget *hbuttonbox23;
  GtkWidget *separatortoolitem8;
  GtkWidget *button299;
  GtkWidget *alignment229;
  GtkWidget *hbox229;
  GtkWidget *image260;
  GtkWidget *label878;
  GtkWidget *button300;
  GtkWidget *alignment230;
  GtkWidget *hbox230;
  GtkWidget *image261;
  GtkWidget *label879;
  GtkWidget *button301;
  GtkWidget *alignment231;
  GtkWidget *hbox231;
  GtkWidget *image262;
  GtkWidget *label880;
  GtkWidget *button302;
  GtkWidget *alignment232;
  GtkWidget *hbox232;
  GtkWidget *image263;
  GtkWidget *label881;
  GtkWidget *label882;
  GtkWidget *conf_supp_elec_button;
  GtkWidget *alignment234;
  GtkWidget *hbox234;
  GtkWidget *image265;
  GtkWidget *label885;
  GtkWidget *id_supp_election_entry;
  GtkWidget *prcd_supp_election;
  GtkWidget *n_supp_elec_button;
  GSList *n_supp_elec_button_group = NULL;
  GtkWidget *o_supp_elec_button;
  GtkWidget *labelsupp;
  GtkWidget *label890;
  GtkWidget *label889;

  supprimer_election_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer_election_), _("supprimer election "));

  fixed82 = gtk_fixed_new ();
  gtk_widget_show (fixed82);
  gtk_container_add (GTK_CONTAINER (supprimer_election_), fixed82);

  hbuttonbox23 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox23);
  gtk_fixed_put (GTK_FIXED (fixed82), hbuttonbox23, 288, 16);
  gtk_widget_set_size_request (hbuttonbox23, 255, 29);

  separatortoolitem8 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem8);
  gtk_fixed_put (GTK_FIXED (fixed82), separatortoolitem8, 104, 296);
  gtk_widget_set_size_request (separatortoolitem8, 16, 16);

  button299 = gtk_button_new ();
  gtk_widget_show (button299);
  gtk_fixed_put (GTK_FIXED (fixed82), button299, 16, 16);
  gtk_widget_set_size_request (button299, 128, 40);

  alignment229 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment229);
  gtk_container_add (GTK_CONTAINER (button299), alignment229);

  hbox229 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox229);
  gtk_container_add (GTK_CONTAINER (alignment229), hbox229);

  image260 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image260);
  gtk_box_pack_start (GTK_BOX (hbox229), image260, FALSE, FALSE, 0);

  label878 = gtk_label_new_with_mnemonic (_("accueil "));
  gtk_widget_show (label878);
  gtk_box_pack_start (GTK_BOX (hbox229), label878, FALSE, FALSE, 0);

  button300 = gtk_button_new ();
  gtk_widget_show (button300);
  gtk_fixed_put (GTK_FIXED (fixed82), button300, 488, 16);
  gtk_widget_set_size_request (button300, 136, 40);

  alignment230 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment230);
  gtk_container_add (GTK_CONTAINER (button300), alignment230);

  hbox230 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox230);
  gtk_container_add (GTK_CONTAINER (alignment230), hbox230);

  image261 = gtk_image_new_from_stock ("gtk-connect", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image261);
  gtk_box_pack_start (GTK_BOX (hbox230), image261, FALSE, FALSE, 0);

  label879 = gtk_label_new_with_mnemonic (_("Se deconnecter "));
  gtk_widget_show (label879);
  gtk_box_pack_start (GTK_BOX (hbox230), label879, FALSE, FALSE, 0);

  button301 = gtk_button_new ();
  gtk_widget_show (button301);
  gtk_fixed_put (GTK_FIXED (fixed82), button301, 216, 16);
  gtk_widget_set_size_request (button301, 120, 40);

  alignment231 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment231);
  gtk_container_add (GTK_CONTAINER (button301), alignment231);

  hbox231 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox231);
  gtk_container_add (GTK_CONTAINER (alignment231), hbox231);

  image262 = gtk_image_new_from_stock ("gtk-page-setup", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image262);
  gtk_box_pack_start (GTK_BOX (hbox231), image262, FALSE, FALSE, 0);

  label880 = gtk_label_new_with_mnemonic (_("Administation"));
  gtk_widget_show (label880);
  gtk_box_pack_start (GTK_BOX (hbox231), label880, FALSE, FALSE, 0);

  button302 = gtk_button_new ();
  gtk_widget_show (button302);
  gtk_fixed_put (GTK_FIXED (fixed82), button302, 360, 16);
  gtk_widget_set_size_request (button302, 112, 40);

  alignment232 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment232);
  gtk_container_add (GTK_CONTAINER (button302), alignment232);

  hbox232 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox232);
  gtk_container_add (GTK_CONTAINER (alignment232), hbox232);

  image263 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image263);
  gtk_box_pack_start (GTK_BOX (hbox232), image263, FALSE, FALSE, 0);

  label881 = gtk_label_new_with_mnemonic (_("Profile "));
  gtk_widget_show (label881);
  gtk_box_pack_start (GTK_BOX (hbox232), label881, FALSE, FALSE, 0);

  label882 = gtk_label_new (_("Supprimer election "));
  gtk_widget_show (label882);
  gtk_fixed_put (GTK_FIXED (fixed82), label882, 152, 88);
  gtk_widget_set_size_request (label882, 328, 40);

  conf_supp_elec_button = gtk_button_new ();
  gtk_widget_show (conf_supp_elec_button);
  gtk_fixed_put (GTK_FIXED (fixed82), conf_supp_elec_button, 248, 264);
  gtk_widget_set_size_request (conf_supp_elec_button, 128, 48);

  alignment234 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment234);
  gtk_container_add (GTK_CONTAINER (conf_supp_elec_button), alignment234);

  hbox234 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox234);
  gtk_container_add (GTK_CONTAINER (alignment234), hbox234);

  image265 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image265);
  gtk_box_pack_start (GTK_BOX (hbox234), image265, FALSE, FALSE, 0);

  label885 = gtk_label_new_with_mnemonic (_("confirmer "));
  gtk_widget_show (label885);
  gtk_box_pack_start (GTK_BOX (hbox234), label885, FALSE, FALSE, 0);

  id_supp_election_entry = gtk_entry_new ();
  gtk_widget_show (id_supp_election_entry);
  gtk_fixed_put (GTK_FIXED (fixed82), id_supp_election_entry, 192, 160);
  gtk_widget_set_size_request (id_supp_election_entry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_supp_election_entry), 8226);

  prcd_supp_election = gtk_button_new_with_mnemonic (_("precedent"));
  gtk_widget_show (prcd_supp_election);
  gtk_fixed_put (GTK_FIXED (fixed82), prcd_supp_election, 16, 72);
  gtk_widget_set_size_request (prcd_supp_election, 120, 32);

  n_supp_elec_button = gtk_radio_button_new_with_mnemonic (NULL, _("non"));
  gtk_widget_show (n_supp_elec_button);
  gtk_fixed_put (GTK_FIXED (fixed82), n_supp_elec_button, 352, 232);
  gtk_widget_set_size_request (n_supp_elec_button, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (n_supp_elec_button), n_supp_elec_button_group);
  n_supp_elec_button_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (n_supp_elec_button));

  o_supp_elec_button = gtk_radio_button_new_with_mnemonic (NULL, _("oui"));
  gtk_widget_show (o_supp_elec_button);
  gtk_fixed_put (GTK_FIXED (fixed82), o_supp_elec_button, 264, 232);
  gtk_widget_set_size_request (o_supp_elec_button, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (o_supp_elec_button), n_supp_elec_button_group);
  n_supp_elec_button_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (o_supp_elec_button));

  labelsupp = gtk_label_new ("");
  gtk_widget_show (labelsupp);
  gtk_fixed_put (GTK_FIXED (fixed82), labelsupp, 392, 144);
  gtk_widget_set_size_request (labelsupp, 224, 64);

  label890 = gtk_label_new (_("vous etes sure de supprimer ?"));
  gtk_widget_show (label890);
  gtk_fixed_put (GTK_FIXED (fixed82), label890, 48, 224);
  gtk_widget_set_size_request (label890, 192, 40);

  label889 = gtk_label_new (_("identifiant"));
  gtk_widget_show (label889);
  gtk_fixed_put (GTK_FIXED (fixed82), label889, 96, 160);
  gtk_widget_set_size_request (label889, 96, 24);

  g_signal_connect ((gpointer) conf_supp_elec_button, "clicked",
                    G_CALLBACK (on_conf_supp_elec_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) prcd_supp_election, "clicked",
                    G_CALLBACK (on_prcd_supp_election_clicked),
                    NULL);
  g_signal_connect ((gpointer) n_supp_elec_button, "toggled",
                    G_CALLBACK (on_n_supp_elec_button_toggled),
                    NULL);
  g_signal_connect ((gpointer) o_supp_elec_button, "toggled",
                    G_CALLBACK (on_o_supp_elec_button_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer_election_, supprimer_election_, "supprimer_election_");
  GLADE_HOOKUP_OBJECT (supprimer_election_, fixed82, "fixed82");
  GLADE_HOOKUP_OBJECT (supprimer_election_, hbuttonbox23, "hbuttonbox23");
  GLADE_HOOKUP_OBJECT (supprimer_election_, separatortoolitem8, "separatortoolitem8");
  GLADE_HOOKUP_OBJECT (supprimer_election_, button299, "button299");
  GLADE_HOOKUP_OBJECT (supprimer_election_, alignment229, "alignment229");
  GLADE_HOOKUP_OBJECT (supprimer_election_, hbox229, "hbox229");
  GLADE_HOOKUP_OBJECT (supprimer_election_, image260, "image260");
  GLADE_HOOKUP_OBJECT (supprimer_election_, label878, "label878");
  GLADE_HOOKUP_OBJECT (supprimer_election_, button300, "button300");
  GLADE_HOOKUP_OBJECT (supprimer_election_, alignment230, "alignment230");
  GLADE_HOOKUP_OBJECT (supprimer_election_, hbox230, "hbox230");
  GLADE_HOOKUP_OBJECT (supprimer_election_, image261, "image261");
  GLADE_HOOKUP_OBJECT (supprimer_election_, label879, "label879");
  GLADE_HOOKUP_OBJECT (supprimer_election_, button301, "button301");
  GLADE_HOOKUP_OBJECT (supprimer_election_, alignment231, "alignment231");
  GLADE_HOOKUP_OBJECT (supprimer_election_, hbox231, "hbox231");
  GLADE_HOOKUP_OBJECT (supprimer_election_, image262, "image262");
  GLADE_HOOKUP_OBJECT (supprimer_election_, label880, "label880");
  GLADE_HOOKUP_OBJECT (supprimer_election_, button302, "button302");
  GLADE_HOOKUP_OBJECT (supprimer_election_, alignment232, "alignment232");
  GLADE_HOOKUP_OBJECT (supprimer_election_, hbox232, "hbox232");
  GLADE_HOOKUP_OBJECT (supprimer_election_, image263, "image263");
  GLADE_HOOKUP_OBJECT (supprimer_election_, label881, "label881");
  GLADE_HOOKUP_OBJECT (supprimer_election_, label882, "label882");
  GLADE_HOOKUP_OBJECT (supprimer_election_, conf_supp_elec_button, "conf_supp_elec_button");
  GLADE_HOOKUP_OBJECT (supprimer_election_, alignment234, "alignment234");
  GLADE_HOOKUP_OBJECT (supprimer_election_, hbox234, "hbox234");
  GLADE_HOOKUP_OBJECT (supprimer_election_, image265, "image265");
  GLADE_HOOKUP_OBJECT (supprimer_election_, label885, "label885");
  GLADE_HOOKUP_OBJECT (supprimer_election_, id_supp_election_entry, "id_supp_election_entry");
  GLADE_HOOKUP_OBJECT (supprimer_election_, prcd_supp_election, "prcd_supp_election");
  GLADE_HOOKUP_OBJECT (supprimer_election_, n_supp_elec_button, "n_supp_elec_button");
  GLADE_HOOKUP_OBJECT (supprimer_election_, o_supp_elec_button, "o_supp_elec_button");
  GLADE_HOOKUP_OBJECT (supprimer_election_, labelsupp, "labelsupp");
  GLADE_HOOKUP_OBJECT (supprimer_election_, label890, "label890");
  GLADE_HOOKUP_OBJECT (supprimer_election_, label889, "label889");

  return supprimer_election_;
}

