/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion_election (void);
GtkWidget* create_ajout_election_ (void);
GtkWidget* create_modif_election_ (void);
GtkWidget* create_supprimer_election_ (void);
