/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *gestion_election;
  GtkWidget *ajout_election_;
  GtkWidget *modif_election_;
  GtkWidget *supprimer_election_;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  gestion_election = create_gestion_election ();
  gtk_widget_show (gestion_election);
  /*ajout_election_ = create_ajout_election_ ();
  gtk_widget_show (ajout_election_);
  modif_election_ = create_modif_election_ ();
  gtk_widget_show (modif_election_);
  supprimer_election_ = create_supprimer_election_ ();
  gtk_widget_show (supprimer_election_);*/

  gtk_main ();
  return 0;
}

